Port  kaisen-timeshift-fast-restore to dash

diff --git a/debian/kaisen-timeshift-fast-restore b/debian/kaisen-timeshift-fast-restore
--- a/debian/kaisen-timeshift-fast-restore
+++ b/debian/kaisen-timeshift-fast-restore
@@ -1,28 +1,28 @@
-#!/bin/bash
+#!/bin/sh
 
 RED='\e[1;31m'
+RESETCOLOR='\e[39;49m'
+ERROR="$RED"'Error:'"$RESETCOLOR"
 
-if [ "$EUID" -ne 0 ]; then
-	echo -e $RED "Run this script as root or with the sudo command.";tput init
-	exit 1
+if [ "$(id -u)" -ne 0 ]; then
+    printf "$ERROR Run this script as root or with the sudo command.\n"1>&2;tput init
+    exit 1
 fi
 
 if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
-	echo -e $RED "Running in chroot, ignore the snapshot creation request.";tput init
-	exit 1
+    printf "$ERROR Running in chroot, ignore the snapshot creation request.\n"1>&2;tput init
+    exit 1
 fi
 
 if ! command -v timeshift > /dev/null; then
-	exit 1
+    exit 1
 fi
 
-cat /proc/cmdline | grep kaisen-grub-btrfs > /dev/null
-
-if [ $? -ne 0 ]; then
-	echo -e $RED "You have not booted from a snapshot. Aborting.";tput init
-	exit 1
+if grep kaisen-grub-btrfs < /proc/cmdline > /dev/null; then
+    printf "$ERROR You have not booted from a snapshot. Aborting.\n" 1>&2;tput init
+    exit 1
 fi
 
-SNAPSHOT=`awk -F 'subvol=timeshift-btrfs/snapshots/' '{ print $2 }' /proc/cmdline | cut -d '/' -f1`
+SNAPSHOT=$(awk -F 'subvol=timeshift-btrfs/snapshots/' '{ print $2 }' /proc/cmdline | cut -d '/' -f1)
 
 timeshift --yes --scripted --btrfs --restore --snapshot "$SNAPSHOT"
